apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-32a6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-32a6
    app.kubernetes.io/part-of: tkrw-pr712-0075-0004-app
  name: devfile-sample-32a6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-32a6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-32a6
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-32a6@sha256:9b687e3012c41c915eac6e4462dc7f0dbe3c0c9d04fb8f898ebd054f4375cbdc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
